### ISSUE TITLE
Crash at adapter alias-manager

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.repochecker#237]
checkTests [E3xx]
GLOBAL ERROR: AxiosError: Request failed with status code 404, {"message":"Request failed with status code 404","name":"AxiosError","stack":"AxiosError: Request failed with status code 404\n    at settle (C:\\GitHub\\iobroker\\ioBroker.repochecker\\node_modules\\axios\\dist\\node\\axios.cjs:1983:12)\n    at IncomingMessage.handleStreamEnd (C:\\GitHub\\iobroker\\ioBroker.repochecker\\node_modules\\axios\\dist\\node\\axios.cjs:3085:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (C:\\GitHub\\iobroker\\ioBroker.repochecker\\node_modules\\axios\\dist\\node\\axios.cjs:4224:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http","fetch"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Cache-Control":"no-cache","Pragma":"no-cache","Expires":"0","User-Agent":"axios/1.7.2","Accept-Encoding":"gzip, compress, deflate, br"},"url":"https://api.travis-ci.org/sbormann/ioBroker.alias-manager.png","method":"get"},"code":"ERR_BAD_REQUEST","status":404}
Errors found

########## SUMMARY ##########

Errors:
[E036] @iobroker/testing 2.2.0 specified. 4.1.3 is required as minimum,  4.1.3 is recommended. Please update devDependencies at package.json
[E999] GLOBAL ERROR: AxiosError: Request failed with status code 404, {"message":"Request failed with status code 404","name":"AxiosError","stack":"AxiosError: Request failed with status code 404\n    at settle (C:\\GitHub\\iobroker\\ioBroker.repochecker\\node_modules\\axios\\dist\\node\\axios.cjs:1983:12)\n    at IncomingMessage.handleStreamEnd (C:\\GitHub\\iobroker\\ioBroker.repochecker\\node_modules\\axios\\dist\\node\\axios.cjs:3085:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (C:\\GitHub\\iobroker\\ioBroker.repochecker\\node_modules\\axios\\dist\\node\\axios.cjs:4224:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http","fetch"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Cache-Control":"no-cache","Pragma":"no-cache","Expires":"0","User-Agent":"axios/1.7.2","Accept-Encoding":"gzip, compress, deflate, br"},"url":"https://api.travis-ci.org/sbormann/ioBroker.alias-manager.png","method":"get"},"code":"ERR_BAD_REQUEST","status":404}

Warnings:
[W040] "keywords" within package.json should contain "ioBroker"
[W105] Missing suggested translation into uk of "common.titleLang" in io-package.json.
[W109] Missing suggested translation into uk of "common.desc" in io-package.json.
[W130] Many "common.news" found in io-package.json. Repositorybuilder will truncate at 7 news. Please remove old news.
[W145] Missing suggested translation into uk of some "common.news" in io-package.json.
[W181] "common.license" in io-package.json is deprecated. Please define object "common.licenseInformation"
[W184] "common.main" is deprecated and ignored. Please remove from io-package.json. Use "main" at package.json instead.
[W184] "common.materialize" is deprecated for admin >= 5 at io-package.json. Please use property "adminUI".
[W184] "common.materializeTab" is deprecated for admin >= 5 at io-package.json. Please use property "adminUI".
[W184] "common.title" is deprecated and replaced by "common.titleLang". Please remove from io-package.json.
[W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package
[W522] Please consider migrating to admin 5 UI (jsonConfig).

C:\GitHub\iobroker\ioBroker.repochecker>

**Comment by mcm1957** [comment]
tryvis check no longer working - has been removed
